from datetime import datetime
from typing import Any

from config.settings import ChirpSettings
from utils.time_utils import format_duration, format_meeting_time

MEETING_SECTION_TEMPLATE = """## {meeting_title}

**Time:** {meeting_time}
**Duration:** {duration}

### Executive Summary

{executive_summary}

### Agenda

{agenda}

### Discussion Highlights

{discussion_highlights}

### Action Items

{action_items}

### Decisions Made

{decisions}

### Open Questions

{open_questions}

### Next Steps

{next_steps}

---"""


DAILY_NOTES_TEMPLATE = """# Meeting Notes - {date}

{meeting_sections}

---
*Generated by Chirp*
*Total meetings: {meeting_count} | Total duration: {total_duration}*"""


class TemplateEngine:
    def __init__(self, settings: ChirpSettings):
        self.settings = settings

    def render_daily_notes(
        self,
        date: datetime,
        meeting_sections: list[str],
        meeting_count: int,
        total_duration: float,
    ) -> str:
        variables = {
            "date": date.strftime("%B %d, %Y"),
            "meeting_sections": "\n\n".join(meeting_sections),
            "meeting_count": meeting_count,
            "total_duration": format_duration(total_duration),
        }
        return _substitute_variables(DAILY_NOTES_TEMPLATE, variables)

    def render_meeting_section(self, meeting_data: dict[str, Any]) -> str:
        metadata = meeting_data.get("metadata", {})
        meeting_time = _extract_meeting_time(metadata)
        duration = metadata.get("duration", 0)
        duration_str = format_duration(duration) if duration else "Unknown"

        variables = {
            "meeting_title": meeting_data.get("meeting_title", "Untitled Meeting"),
            "meeting_time": meeting_time,
            "duration": duration_str,
            "executive_summary": meeting_data.get(
                "executive_summary", "No summary available"
            ),
            "agenda": _format_list_items(meeting_data.get("agenda", [])),
            "discussion_highlights": _format_list_items(
                meeting_data.get("discussion_highlights", [])
            ),
            "action_items": _format_list_items(meeting_data.get("action_items", [])),
            "decisions": _format_list_items(meeting_data.get("decisions", [])),
            "open_questions": _format_list_items(
                meeting_data.get("open_questions", [])
            ),
            "next_steps": _format_list_items(meeting_data.get("next_steps", [])),
        }

        return _substitute_variables(MEETING_SECTION_TEMPLATE, variables)


def _substitute_variables(template: str, variables: dict[str, Any]) -> str:
    result = template
    for key, value in variables.items():
        result = result.replace(f"{{{key}}}", str(value))
    return result


def _format_list_items(items: list[str]) -> str:
    if not items:
        return "None"
    return "\n".join(f"- {item}" for item in items)


def _extract_meeting_time(metadata: dict[str, Any]) -> str:
    raw = metadata.get("date") or metadata.get("recorded_at")
    if isinstance(raw, datetime):
        return format_meeting_time(raw)
    if isinstance(raw, str):
        try:
            meeting_datetime = datetime.fromisoformat(raw.replace("Z", "+00:00"))
            return format_meeting_time(meeting_datetime)
        except ValueError:
            return "Unknown time"
    return "Unknown time"
