import re
from datetime import datetime
from typing import Any

from config.settings import ChirpSettings
from utils.time_utils import format_duration, format_meeting_time


class TemplateEngine:
    def __init__(self, settings: ChirpSettings):
        self.settings = settings
        self.template_dir = settings.directories.templates

    def load_template(self, template_name: str) -> str:
        template_path = self.template_dir / template_name

        if not template_path.exists():
            return self._get_default_template(template_name)

        try:
            with open(template_path, encoding="utf-8") as f:
                return f.read()
        except Exception:
            return self._get_default_template(template_name)

    def render_daily_notes(
        self,
        date: datetime,
        meeting_sections: list[str],
        meeting_count: int,
        total_duration: float,
    ) -> str:
        template = self.load_template("daily_notes.md")

        variables = {
            "date": date.strftime("%B %d, %Y"),
            "meeting_sections": "\n\n".join(meeting_sections),
            "meeting_count": meeting_count,
            "total_duration": format_duration(total_duration),
        }

        return self._substitute_variables(template, variables)

    def render_meeting_section(self, meeting_data: dict[str, Any]) -> str:
        template = self.load_template("meeting_section.md")

        recorded_at = meeting_data.get("metadata", {}).get("recorded_at")
        if recorded_at:
            try:
                meeting_datetime = datetime.fromisoformat(
                    recorded_at.replace("Z", "+00:00")
                )
                meeting_time = format_meeting_time(meeting_datetime)
            except Exception:
                meeting_time = "Unknown time"
        else:
            meeting_time = "Unknown time"

        duration = meeting_data.get("metadata", {}).get("duration", 0)
        duration_str = format_duration(duration) if duration else "Unknown"

        variables = {
            "meeting_title": meeting_data.get("meeting_title", "Untitled Meeting"),
            "meeting_time": meeting_time,
            "duration": duration_str,
            "participants": meeting_data.get("participants", "Not specified"),
            "executive_summary": meeting_data.get(
                "executive_summary", "No summary available"
            ),
            "key_points": self._format_list_items(meeting_data.get("key_points", [])),
            "decisions": self._format_list_items(meeting_data.get("decisions", [])),
            "action_items": self._format_list_items(
                meeting_data.get("action_items", [])
            ),
            "next_steps": self._format_list_items(meeting_data.get("next_steps", [])),
        }

        return self._substitute_variables(template, variables)

    def _substitute_variables(self, template: str, variables: dict[str, Any]) -> str:
        result = template

        for key, value in variables.items():
            pattern = f"{{{key}}}"
            result = result.replace(pattern, str(value))

        return result

    def _format_list_items(self, items: list[str]) -> str:
        if not items:
            return "None"

        return "\n".join(f"- {item}" for item in items)

    def _get_default_template(self, template_name: str) -> str:
        templates = {
            "daily_notes.md": """# Meeting Notes - {date}

{meeting_sections}

---
*Generated by Chirp 🐦*
*Total meetings: {meeting_count} | Total duration: {total_duration}*""",
            "meeting_section.md": """## {meeting_title} - {meeting_time}

**Duration:** {duration}
**Participants:** {participants}

### Executive Summary
{executive_summary}

### Key Discussion Points
{key_points}

### Decisions Made
{decisions}

### Action Items
{action_items}

### Next Steps
{next_steps}

---""",
        }

        return templates.get(template_name, f"Template '{template_name}' not found.")

    def create_default_templates(self):
        self.template_dir.mkdir(parents=True, exist_ok=True)

        templates = {
            "daily_notes.md": self._get_default_template("daily_notes.md"),
            "meeting_section.md": self._get_default_template("meeting_section.md"),
        }

        for template_name, content in templates.items():
            template_path = self.template_dir / template_name
            if not template_path.exists():
                try:
                    with open(template_path, "w", encoding="utf-8") as f:
                        f.write(content)
                except Exception:
                    pass

    def validate_template(self, template_name: str) -> dict[str, Any]:
        template_path = self.template_dir / template_name

        if not template_path.exists():
            return {
                "valid": False,
                "error": "Template file does not exist",
                "variables": [],
            }

        try:
            with open(template_path, encoding="utf-8") as f:
                content = f.read()

            variables = re.findall(r"\{(\w+)\}", content)

            return {
                "valid": True,
                "error": None,
                "variables": list(set(variables)),
                "path": str(template_path),
            }

        except Exception as e:
            return {"valid": False, "error": str(e), "variables": []}

    def get_template_info(self) -> dict[str, Any]:
        template_files = list(self.template_dir.glob("*.md"))

        templates_info = {}
        for template_file in template_files:
            info = self.validate_template(template_file.name)
            templates_info[template_file.name] = info

        return {
            "template_directory": str(self.template_dir),
            "templates": templates_info,
            "total_templates": len(template_files),
        }
